### ISSUE TITLE
TypeError during writing of 58 datasets

### ISSUE THREAD

**Issue by PapaTim68** [openmodal/pyuff#18]
I encountered an TypeError: not all arguments converted during string formatting
while using the pyuff module and writing 58 datasets. Here is the full Traceback:
```
Traceback (most recent call last):
  File "C:\Users\t.papenhaus\Desktop\punch_to_unv\source\pyuff.py", line 993, in _write58
    fh.write((''.join(fmt[remVals]) + '\n') % tuple(data[4 * n4Blocks:]))
TypeError: not all arguments converted during string formatting
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\Software\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-cdf41e57026d>", line 1, in <module>
    runfile('C:/Users/t.papenhaus/Desktop/punch_to_unv/source/main.py', wdir='C:/Users/t.papenhaus/Desktop/punch_to_unv/source')
  File "D:\Software\PyCharm\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\Software\PyCharm\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/t.papenhaus/Desktop/punch_to_unv/source/main.py", line 71, in <module>
    uffcon.uff_to_global_to_target_local("../Combine__SLL-2Z__Glob.unv")
  File "C:\Users\t.papenhaus\Desktop\punch_to_unv\source\uff_converter.py", line 556, in uff_to_global_to_target_local
    pyuff.UFF(out_path_plus_minus).write_sets(set_plus_minus, "overwrite")
  File "C:\Users\t.papenhaus\Desktop\punch_to_unv\source\pyuff.py", line 502, in write_sets
    self._write_set(dsets[ii], 'add')
  File "C:\Users\t.papenhaus\Desktop\punch_to_unv\source\pyuff.py", line 619, in _write_set
    self._write58(fh, dset, mode)
  File "C:\Users\t.papenhaus\Desktop\punch_to_unv\source\pyuff.py", line 1018, in _write58
    raise UFFException('Error writing data-set #58')
pyuff.UFFException: Error writing data-set #58

```
I also might have a solution for the problem. I made use of the new python string Formatting and replaced line 993. Which was like so : `fh.write((''.join(fmt[remVals]) + '\n') % tuple(data[4 * n4Blocks:]))`
with the following `fh.write((''.join(fmt[remVals]) + '\n').format(data[4 * n4Blocks:]))`. This "fixes" the probelm but I havent yet tested it fully and since I am at Work and have no real Git access except the Browser I cant make a Pull request and change it my self.

**Comment by jankoslavic** [comment]
Hi @PapaTim68 please provide a snippet example uff file and I will add it to the tests (including your proposed solution)

**Comment by PapaTim68** [comment]
I would like to give you an Examble to use but I am not allowed to give away the data used and since I am not 100% sure what caused the bug I cant make a Dummy file which causes the same Problem. I will look what I can do.

**Comment by jankoslavic** [comment]
I am closing this issue; @PapaTim68 if you send me a snippet file with the problem, I can look into details.
